name: Build-Tauri-Ultra-Light
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Build Application
        run: |
          tauri init --app-name "MonApp" --window-title "Mon App" --frontend-dist "../dist" --before-dev-command "" --before-build-command "" --ci --yes
          tauri build
        
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Logiciel-Poids-Plume
          path: src-tauri/target/release/MonApp.exe
