name: Build-Tauri-2026
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # On utilise une version stable et récente

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Create App
        shell: bash
        run: |
          # On installe l'outil Tauri localement pour éviter les conflits
          npm install @tauri-apps/cli @tauri-apps/api
          
          # On force l'initialisation SANS dossier src-tauri préalable
          npx tauri init --app-name "MonApp" --window-title "Mon App" --frontend-dist "../dist" --ci --yes
          
          # On lance la compilation
          npx tauri build
        
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Mon-Logiciel-Mini
          path: src-tauri/target/release/MonApp.exe
